
package cxf.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CxfIService", targetNamespace = "http://service.cxf/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CxfIService {


    /**
     * 
     * @param secondNum
     * @param firstNum
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "sumResult", targetNamespace = "")
    @RequestWrapper(localName = "sum", targetNamespace = "http://service.cxf/", className = "cxf.service.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://service.cxf/", className = "cxf.service.SumResponse")
    public int sum(
        @WebParam(name = "firstNum", targetNamespace = "")
        int firstNum,
        @WebParam(name = "secondNum", targetNamespace = "")
        int secondNum);

    /**
     * 
     * @param secondNum
     * @param firstNum
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "multiplyResult", targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://service.cxf/", className = "cxf.service.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://service.cxf/", className = "cxf.service.MultiplyResponse")
    public int multiply(
        @WebParam(name = "firstNum", targetNamespace = "")
        int firstNum,
        @WebParam(name = "secondNum", targetNamespace = "")
        int secondNum);

    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns cxf.service.User
     */
    @WebMethod
    @WebResult(name = "loginUserInfo", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.cxf/", className = "cxf.service.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.cxf/", className = "cxf.service.LoginResponse")
    public User login(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
