
package cxf.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CxfIServiceService", targetNamespace = "http://service.cxf/", wsdlLocation = "http://localhost:9093/cxf_services?wsdl")
public class CxfIServiceService
    extends Service
{

    private final static URL CXFISERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CXFISERVICESERVICE_EXCEPTION;
    private final static QName CXFISERVICESERVICE_QNAME = new QName("http://service.cxf/", "CxfIServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9093/cxf_services?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CXFISERVICESERVICE_WSDL_LOCATION = url;
        CXFISERVICESERVICE_EXCEPTION = e;
    }

    public CxfIServiceService() {
        super(__getWsdlLocation(), CXFISERVICESERVICE_QNAME);
    }

    public CxfIServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CXFISERVICESERVICE_QNAME, features);
    }

    public CxfIServiceService(URL wsdlLocation) {
        super(wsdlLocation, CXFISERVICESERVICE_QNAME);
    }

    public CxfIServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CXFISERVICESERVICE_QNAME, features);
    }

    public CxfIServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CxfIServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CxfIService
     */
    @WebEndpoint(name = "CxfIServicePort")
    public CxfIService getCxfIServicePort() {
        return super.getPort(new QName("http://service.cxf/", "CxfIServicePort"), CxfIService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CxfIService
     */
    @WebEndpoint(name = "CxfIServicePort")
    public CxfIService getCxfIServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cxf/", "CxfIServicePort"), CxfIService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CXFISERVICESERVICE_EXCEPTION!= null) {
            throw CXFISERVICESERVICE_EXCEPTION;
        }
        return CXFISERVICESERVICE_WSDL_LOCATION;
    }

}
